# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Docker Hub to avoid pull rate limits...
#       - echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
#       - echo Logging in to Amazon ECR...
#       - aws --version
#       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
#       - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - docker build -t $REPOSITORY_URI:latest .
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo Writing imagedefinitions.json...
#       - printf '[{"name":"%s","imageUri":"%s:%s"}]' "$SERVICE_NAME" "$REPOSITORY_URI" "$IMAGE_TAG" > imagedefinitions.json
# artifacts:
#   files:
#     - imagedefinitions.json



version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1 # change as needed
    REPOSITORY_URI: 302263040839.dkr.ecr.ap-south-1.amazonaws.com/sample-app-repo
    SERVICE_NAME: sample-app-service # must match container name in ECS task definition
    CLUSTER_NAME: sample-app-cluster
    CONTAINER_NAME: sample-app-service

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub to avoid pull rate limits...
      - echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      # Using jq to ensure valid JSON format without trailing newline or bad escaping
      - echo "[{\"name\":\"$SERVICE_NAME\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" | jq -c . > imagedefinitions.json
      - echo Contents of imagedefinitions.json:
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
